CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS users (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  email varchar,
  CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiator_id int8 REFERENCES users (id),
  annotation varchar NOT NULL,
  category_id int8 REFERENCES categories (id),
  description varchar,
  eventDate timestamp NOT NULL,
  location varchar NOT NULL,
  paid boolean,
  participantLimit int4,
  requestModeration boolean,
  title varchar NOT NULL
);
