CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS states (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS users (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  email varchar,
  CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lat varchar NOT NULL CHECK (lat <> ''),
  lon varchar NOT NULL CHECK (lon <> '')
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  initiator_id int8 REFERENCES users (id),
  annotation varchar NOT NULL,
  category_id int8 REFERENCES categories (id),
  description text,
  event_date timestamp NOT NULL,
  created_on timestamp NOT NULL,
  location_id int8 REFERENCES locations (id),
  paid boolean,
  participant_limit int4,
  request_moderation boolean,
  title varchar NOT NULL,
  state_id int8 REFERENCES states (id)
);

CREATE TABLE IF NOT EXISTS request_status (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id int8 REFERENCES events (id),
  requester_id int8 REFERENCES users (id),
  status_id int8 REFERENCES request_status (id),
  created_on timestamp NOT NULL
);
